# Pinned to current baseline (2026-05-24). Each entry suppresses pre-existing
# dialyzer warnings unrelated to recent memory module work. Uses {file, warning_type}
# tuples (line-agnostic) so refactors within the same file/check don't break CI.
[
  # CI-only baseline (PLT cache differs from local). Math engine uses Rustler NIFs
  # whose types dialyzer can't see through.
  {"lib/backplane/math/engine/native.ex", :call_without_opaque},
  {"lib/backplane/math/sandbox.ex", :call_without_opaque},
  {"lib/backplane_web/live/provider_new_live.ex", :pattern_match_cov},
  {"lib/backplane_web/live/provider_show_live.ex", :pattern_match_cov},
  {"lib/backplane_web/live/settings_live.ex", :unused_fun},
  {"lib/backplane_web/live/skill_live.ex", :call},
  {"lib/backplane/cache.ex", :invalid_contract},
  {"lib/backplane/clients.ex", :unknown_type},
  {"lib/backplane/host_agent/checksum.ex", :call},
  {"lib/backplane/host_agent/installer.ex", :pattern_match},
  {"lib/backplane/host_agent/installer.ex", :unused_fun},
  {"lib/backplane/host_agent/reporter.ex", :pattern_match},
  {"lib/backplane/host_agent/skill_bundle.ex", :pattern_match},
  {"lib/backplane/llm/model_alias.ex", :call},
  {"lib/backplane/llm/model_alias.ex", :invalid_contract},
  {"lib/backplane/llm/model_alias.ex", :no_return},
  {"lib/backplane/llm/model_alias.ex", :unused_fun},
  {"lib/backplane/llm/router.ex", :pattern_match},
  {"lib/backplane/llm/router.ex", :unused_fun},
  {"lib/backplane/math/config.ex", :unknown_type},
  {"lib/backplane/proxy/upstream.ex", :pattern_match_cov},
  {"lib/backplane/services/web_fetch.ex", :guard_fail},
  {"lib/backplane/services/web_fetch.ex", :pattern_match_cov},
  {"lib/backplane/services/web_search.ex", :pattern_match_cov},
  {"lib/backplane/services/web_search.ex", :pattern_match},
  {"lib/backplane/settings/credentials.ex", :unknown_type},
  {"lib/backplane/skills.ex", :pattern_match},
  {"lib/backplane/skills.ex", :unused_fun},
  {"lib/backplane/skills/api_router.ex", :call},
  {"lib/backplane/skills/api_router.ex", :no_return},
  {"lib/backplane/skills/api_router.ex", :pattern_match},
  {"lib/backplane/skills/api_router.ex", :unused_fun},
  {"lib/backplane/skills/archive.ex", :pattern_match},
  {"lib/backplane/skills/blob/local_fs.ex", :call},
  {"lib/backplane/skills/blob/local_fs.ex", :pattern_match},
  {"lib/backplane/skills/export.ex", :pattern_match},
  {"lib/backplane/skills/host_agent_api_router.ex", :pattern_match},
  {"lib/backplane/skills/host_agent_api_router.ex", :unused_fun},
  {"lib/backplane/tools/skill.ex", :pattern_match},
  {"lib/backplane/tools/skill.ex", :unused_fun}
]
