# Pinned to the current CI baseline. Entries are line-agnostic so normal edits
# inside the same file do not invalidate the ignore list.
[
  {"lib/backplane/api/controllers/auth/login_controller.ex", :pattern_match_cov},
  {"lib/backplane/auth/audit.ex", :call_without_opaque},
  {"lib/backplane/auth/tokens.ex", :call},
  {"lib/backplane/auth/tokens.ex", :no_return},
  {"lib/backplane/auth/tokens.ex", :pattern_match_cov},
  {"lib/backplane/cache.ex", :invalid_contract},
  {"lib/backplane/admin/live/memory_graph_live.ex", :call},
  {"lib/backplane/admin/live/memory_graph_live.ex", :no_return},
  {"lib/backplane/admin/live/provider_new_live.ex", :pattern_match_cov},
  {"lib/backplane/admin/live/provider_show_live.ex", :pattern_match_cov},
  {"lib/backplane/admin/live/settings_live.ex", :pattern_match},
  {"lib/backplane/admin/live/settings_live.ex", :unused_fun},
  {"lib/backplane/clients.ex", :unknown_type},
  {"lib/backplane/host_agent/config.ex", :pattern_match_cov},
  {"lib/backplane/host_agent/memory_proxy.ex", :call_without_opaque},
  {"lib/backplane/host_agent/reporter.ex", :pattern_match},
  {"lib/backplane/host_agent/services/math.ex", :pattern_match_cov},
  {"lib/backplane/host_agent/skill_bundle.ex", :pattern_match},
  {"lib/backplane/llm/model_alias.ex", :call},
  {"lib/backplane/llm/model_alias.ex", :invalid_contract},
  {"lib/backplane/llm/model_alias.ex", :no_return},
  {"lib/backplane/llm/model_alias.ex", :unused_fun},
  {"lib/backplane/llm/router.ex", :pattern_match},
  {"lib/backplane/llm/router.ex", :unused_fun},
  {"lib/backplane/math/config.ex", :unknown_type},
  {"lib/backplane/math/engine/native.ex", :call_without_opaque},
  {"lib/backplane/math/sandbox.ex", :call_without_opaque},
  {"lib/backplane/monitor.ex", :unknown_type},
  {"lib/backplane/monitor/plan_server.ex", :unknown_type},
  {"lib/backplane/monitor/plan_supervisor.ex", :unknown_type},
  {"lib/backplane/monitor/providers/google_antigravity.ex", :guard_fail},
  {"lib/backplane/monitor/providers/google_antigravity.ex", :pattern_match},
  {"lib/backplane/monitor/providers/openai_codex.ex", :guard_fail},
  {"lib/backplane/monitor/usage_fetcher.ex", :guard_fail},
  {"lib/backplane/monitor/usage_fetcher.ex", :unknown_type},
  {"lib/backplane/proxy/upstream.ex", :pattern_match_cov},
  {"lib/backplane/services/web_live_search.ex", :pattern_match_cov},
  {"lib/backplane/services/web_fetch.ex", :guard_fail},
  {"lib/backplane/services/web_fetch.ex", :pattern_match_cov},
  {"lib/backplane/services/web_search.ex", :pattern_match},
  {"lib/backplane/services/web_search.ex", :pattern_match_cov},
  {"lib/backplane/services/web_x_search.ex", :pattern_match},
  {"lib/backplane/services/web_x_search.ex", :pattern_match_cov},
  {"lib/backplane/settings/credentials.ex", :unknown_type},
  {"lib/backplane/settings/credentials/vault.ex", :unknown_type},
  {"lib/backplane/settings/oauth_refresher.ex", :pattern_match},
  {"lib/backplane/skills.ex", :pattern_match},
  {"lib/backplane/skills/agent_manage.ex", :pattern_match_cov},
  {"lib/backplane/skills/api_router.ex", :call},
  {"lib/backplane/skills/api_router.ex", :no_return},
  {"lib/backplane/skills/api_router.ex", :pattern_match},
  {"lib/backplane/skills/archive.ex", :pattern_match},
  {"lib/backplane/skills/blob/local_fs.ex", :call},
  {"lib/backplane/skills/blob/local_fs.ex", :pattern_match},
  {"lib/backplane/skills/export.ex", :pattern_match},
  {"lib/backplane/transport/mcp_handler.ex", :pattern_match},
  {"lib/backplane_data_case.ex", :unknown_function},
  # Remove once elixir-lang/elixir#15063 is in the CI runtime; see elixir-ecto/ecto#4707.
  {"lib/backplane/memory/events/store.ex",
   "Type mismatch in call without opaque term in append_multi."},
  {"lib/backplane/memory/observations.ex",
   "Type mismatch in call without opaque term in append_multi."},
  {"lib/backplane/memory/observations.ex",
   "Type mismatch in call without opaque term in run."},
  {"lib/backplane/memory/observations.ex",
   "Type mismatch in call without opaque term in update_all."},
  # OTP 28 / Elixir nominal opacity false positives; keep strict warning matches exact.
  {"lib/backplane/host_agent/memory/import.ex",
   "Type mismatch in call without opaque term in member?."},
  {"lib/backplane/host_agent/memory/import.ex",
   "Type mismatch in call with opaque term in walk."},
  {"lib/backplane/memory/memories/relation_classifier.ex",
   "Type mismatch in call without opaque term in disjoint?."},
  {"lib/backplane/memory/memories/relations.ex",
   "Type mismatch in call without opaque term in member?."},
  {"lib/backplane/memory/memories/relations.ex",
   "Type mismatch in call with opaque term in supersession_reaches?."},
  {"lib/backplane/memory/memories/verification.ex",
   "Type mismatch in call without opaque term in member?."},
  {"lib/backplane/memory/recall/reranker.ex",
   "Type mismatch in call without opaque term in await."},
  {"lib/backplane/memory/recall/reranker.ex",
   "Type mismatch in call without opaque term in yield."},
  {"lib/backplane/memory/workers/crystal_worker.ex",
   "Type mismatch in call without opaque term in yield_build_task."},
  {"lib/backplane/memory/workers/crystal_worker.ex",
   "Type mismatch in call without opaque term in shutdown."},
  {"lib/backplane/memory/workers/crystal_worker.ex",
   "Type mismatch in call without opaque term in yield."},
  {"lib/backplane/proxy/tool_catalog.ex",
   "Type mismatch in call without opaque term in member?."},
  {"lib/backplane/proxy/tool_catalog.ex",
   "Type mismatch in call with opaque term in fetch_pages."},
  {"lib/backplane/skills/agent_manage.ex",
   "Type mismatch in call without opaque term in member?."},
  {"lib/backplane/transport/idempotency.ex",
   "Type mismatch in call without opaque term in member?."},
  {"lib/backplane/transport/idempotency.ex",
   "Type mismatch in call with opaque term in normalize_replay_headers."},
  {"lib/backplane/transport/idempotency.ex", "Type mismatch in call without opaque term in put."},
  {"lib/backplane/memory/graph/bfs.ex", :unknown_type},
  {"lib/backplane/memory/memories.ex", :pattern_match_cov},
  {"lib/backplane/memory/service.ex", :pattern_match_cov},
  {"lib/backplane/mcp_protocol.ex", :call},
  {"lib/backplane/mcp_protocol.ex", :no_return},
  {"lib/backplane/mcp_protocol/client.ex", :call},
  {"lib/backplane/mcp_protocol/client.ex", :no_return},
  {"lib/backplane/mcp_protocol/http.ex", :call},
  {"lib/backplane/mcp_protocol/mcp/message.ex", :call},
  {"lib/backplane/mcp_protocol/mcp/message.ex", :no_return},
  {"lib/backplane/mcp_protocol/server/authorization.ex", :call},
  {"lib/backplane/mcp_protocol/server/authorization.ex", :no_return},
  {"lib/backplane/mcp_protocol/server/session.ex", :call},
  {"lib/backplane/mcp_protocol/server/session.ex", :no_return},
  {"lib/backplane/mcp_protocol/server/transport/sse.ex", :call},
  {"lib/backplane/mcp_protocol/server/transport/sse.ex", :no_return},
  {"lib/backplane/mcp_protocol/server/transport/stdio.ex", :call},
  {"lib/backplane/mcp_protocol/server/transport/stdio.ex", :no_return},
  {"lib/backplane/mcp_protocol/server/transport/streamable_http.ex", :call},
  {"lib/backplane/mcp_protocol/server/transport/streamable_http.ex", :no_return},
  {"lib/backplane/mcp_protocol/transport/sse.ex", :call},
  {"lib/backplane/mcp_protocol/transport/sse.ex", :no_return},
  {"lib/backplane/mcp_protocol/transport/websocket.ex", :call},
  {"lib/backplane/mcp_protocol/transport/websocket.ex", :no_return},
  {"lib/mix/tasks/agent.memory.resync.ex", :callback_info_missing},
  {"lib/mix/tasks/agent.memory.resync.ex", :unknown_function},
  {"lib/mix/tasks/agent.memory.tombstones.ex", :callback_info_missing},
  {"lib/mix/tasks/agent.memory.tombstones.ex", :unknown_function},
  {"lib/mix/tasks/agent.run.ex", :callback_info_missing},
  {"lib/mix/tasks/agent.run.ex", :pattern_match_cov},
  {"lib/mix/tasks/agent.run.ex", :unknown_function},
  {"lib/mix/tasks/memory.connect.ex", :callback_info_missing},
  {"lib/mix/tasks/memory.connect.ex", :unknown_function},
  {"lib/mix/tasks/memory.eval.ex", :callback_info_missing},
  {"lib/mix/tasks/memory.eval.ex", :unknown_function},
  {"lib/mix/tasks/memory.seed_bench.ex", :callback_info_missing},
  {"lib/mix/tasks/memory.seed_bench.ex", :unknown_function},
  {"lib/mix/tasks/sse.interactive.ex", :callback_info_missing},
  {"lib/mix/tasks/stdio.interactive.ex", :callback_info_missing},
  {"lib/mix/tasks/streamable_http.interactive.ex", :callback_info_missing},
  {"lib/mix/tasks/websocket.interactive.ex", :callback_info_missing},
  {"lib/relayixir/proxy/http_plug.ex", :pattern_match_cov},
  {"lib/relayixir/proxy/websocket/bridge.ex", :pattern_match},
  {"lib/relayixir/proxy/websocket/bridge.ex", :unused_fun},
  {"lib/relayixir/proxy/websocket/upstream_client.ex", :pattern_match}
]
