defmodule Backplane.Docs.Parsers.HexDocs do
  @moduledoc """
  Parser for ExDoc-generated documentation artifacts.

  Handles HTML files from `doc/` directories generated by `mix docs`.
  Extracts module documentation, function documentation, and guides
  from ExDoc HTML output by stripping tags and splitting by sections.
  """

  @behaviour Backplane.Docs.Parser

  require Logger

  @impl true
  def parse(content, source_path) do
    chunks = extract_chunks(content, source_path)
    {:ok, chunks}
  rescue
    e ->
      Logger.warning("Failed to parse HexDocs #{source_path}: #{Exception.message(e)}")
      {:ok, []}
  end

  defp extract_chunks(content, source_path) do
    cond do
      String.contains?(source_path, "/api-reference") ->
        # API reference pages — skip, individual module pages have the content
        []

      module_page?(source_path) ->
        parse_module_page(content, source_path)

      guide_page?(source_path) ->
        parse_guide_page(content, source_path)

      true ->
        parse_generic_html(content, source_path)
    end
  end

  defp module_page?(path) do
    # ExDoc module pages are like: doc/Foo.Bar.html or doc/Foo.Bar.Baz.html
    basename = Path.basename(path, ".html")
    String.match?(basename, ~r/^[A-Z][\w.]*$/)
  end

  defp guide_page?(path) do
    ext = Path.extname(path)
    ext in [".html", ".htm"] and not module_page?(path)
  end

  defp parse_module_page(content, source_path) do
    module_name = Path.basename(source_path, ".html")
    sections = split_html_sections(content)

    Enum.flat_map(sections, fn {heading, body} ->
      text = strip_html_tags(body) |> String.trim()

      if String.length(text) > 10 do
        {chunk_type, function} = classify_section(heading)

        [
          %{
            source_path: source_path,
            module: module_name,
            function: function,
            chunk_type: chunk_type,
            content: text
          }
        ]
      else
        []
      end
    end)
  end

  defp parse_guide_page(content, source_path) do
    sections = split_html_sections(content)

    Enum.flat_map(sections, fn {heading, body} ->
      text = strip_html_tags(body) |> String.trim()

      if String.length(text) > 10 do
        [
          %{
            source_path: source_path,
            module: nil,
            function: nil,
            chunk_type: "guide",
            content: "## #{strip_html_tags(heading)}\n\n#{text}"
          }
        ]
      else
        []
      end
    end)
  end

  defp parse_generic_html(content, source_path) do
    text = strip_html_tags(content) |> String.trim()

    if String.length(text) > 10 do
      [
        %{
          source_path: source_path,
          module: nil,
          function: nil,
          chunk_type: "guide",
          content: text
        }
      ]
    else
      []
    end
  end

  defp classify_section(heading) do
    heading_text = strip_html_tags(heading) |> String.trim() |> String.downcase()

    cond do
      heading_text == "" or String.contains?(heading_text, "summary") ->
        {"moduledoc", nil}

      String.match?(heading_text, ~r/^([\w?!]+\/\d+)/) ->
        [_, func] = Regex.run(~r/([\w?!]+\/\d+)/, heading_text)
        {"function_doc", func}

      String.contains?(heading_text, "types") ->
        {"typespec", nil}

      String.contains?(heading_text, "callback") ->
        {"function_doc", nil}

      true ->
        {"moduledoc", nil}
    end
  end

  @doc """
  Split HTML content into sections based on heading tags (h1-h4).
  Returns a list of `{heading_html, body_html}` tuples.
  """
  def split_html_sections(html) do
    # Split on h1-h4 tags
    parts = Regex.split(~r/(<h[1-4][^>]*>.*?<\/h[1-4]>)/s, html, include_captures: true)

    parts
    |> chunk_by_headings()
    |> Enum.reject(fn {heading, body} ->
      String.trim(strip_html_tags(heading)) == "" and String.trim(strip_html_tags(body)) == ""
    end)
  end

  defp chunk_by_headings(parts) do
    chunk_by_headings(parts, "", [])
  end

  defp chunk_by_headings([], _current_heading, acc), do: Enum.reverse(acc)

  defp chunk_by_headings([part | rest], current_heading, acc) do
    if Regex.match?(~r/^<h[1-4][^>]*>/s, part) do
      chunk_by_headings(rest, part, acc)
    else
      chunk_by_headings(rest, "", [{current_heading, part} | acc])
    end
  end

  @doc """
  Strip HTML tags from a string, leaving only text content.
  """
  def strip_html_tags(html) do
    html
    |> String.replace(~r/<script[^>]*>.*?<\/script>/s, "")
    |> String.replace(~r/<style[^>]*>.*?<\/style>/s, "")
    |> String.replace(~r/<[^>]+>/, " ")
    |> String.replace(~r/&nbsp;/, " ")
    |> String.replace(~r/&amp;/, "&")
    |> String.replace(~r/&lt;/, "<")
    |> String.replace(~r/&gt;/, ">")
    |> String.replace(~r/&quot;/, "\"")
    |> String.replace(~r/\s+/, " ")
    |> String.trim()
  end
end
