defmodule Backplane.Admin.AudioVoices do
  @moduledoc false

  # MiniMax system voice IDs: https://platform.minimaxi.com/docs/faq/system-voice-id.md
  # Snapshot: 2026-10-06.
  @voices [
    {"male-qn-qingse", "中文 (普通话)", "青涩青年音色"},
    {"male-qn-jingying", "中文 (普通话)", "精英青年音色"},
    {"male-qn-badao", "中文 (普通话)", "霸道青年音色"},
    {"male-qn-daxuesheng", "中文 (普通话)", "青年大学生音色"},
    {"female-shaonv", "中文 (普通话)", "少女音色"},
    {"female-yujie", "中文 (普通话)", "御姐音色"},
    {"female-chengshu", "中文 (普通话)", "成熟女性音色"},
    {"female-tianmei", "中文 (普通话)", "甜美女性音色"},
    {"male-qn-qingse-jingpin", "中文 (普通话)", "青涩青年音色-beta"},
    {"male-qn-jingying-jingpin", "中文 (普通话)", "精英青年音色-beta"},
    {"male-qn-badao-jingpin", "中文 (普通话)", "霸道青年音色-beta"},
    {"male-qn-daxuesheng-jingpin", "中文 (普通话)", "青年大学生音色-beta"},
    {"female-shaonv-jingpin", "中文 (普通话)", "少女音色-beta"},
    {"female-yujie-jingpin", "中文 (普通话)", "御姐音色-beta"},
    {"female-chengshu-jingpin", "中文 (普通话)", "成熟女性音色-beta"},
    {"female-tianmei-jingpin", "中文 (普通话)", "甜美女性音色-beta"},
    {"clever_boy", "中文 (普通话)", "聪明男童"},
    {"cute_boy", "中文 (普通话)", "可爱男童"},
    {"lovely_girl", "中文 (普通话)", "萌萌女童"},
    {"cartoon_pig", "中文 (普通话)", "卡通猪小琪"},
    {"bingjiao_didi", "中文 (普通话)", "病娇弟弟"},
    {"junlang_nanyou", "中文 (普通话)", "俊朗男友"},
    {"chunzhen_xuedi", "中文 (普通话)", "纯真学弟"},
    {"lengdan_xiongzhang", "中文 (普通话)", "冷淡学长"},
    {"badao_shaoye", "中文 (普通话)", "霸道少爷"},
    {"tianxin_xiaoling", "中文 (普通话)", "甜心小玲"},
    {"qiaopi_mengmei", "中文 (普通话)", "俏皮萌妹"},
    {"wumei_yujie", "中文 (普通话)", "妩媚御姐"},
    {"diadia_xuemei", "中文 (普通话)", "嗲嗲学妹"},
    {"danya_xuejie", "中文 (普通话)", "淡雅学姐"},
    {"Chinese (Mandarin)_Reliable_Executive", "中文 (普通话)", "沉稳高管"},
    {"Chinese (Mandarin)_News_Anchor", "中文 (普通话)", "新闻女声"},
    {"Chinese (Mandarin)_Mature_Woman", "中文 (普通话)", "傲娇御姐"},
    {"Chinese (Mandarin)_Unrestrained_Young_Man", "中文 (普通话)", "不羁青年"},
    {"Arrogant_Miss", "中文 (普通话)", "嚣张小姐"},
    {"Robot_Armor", "中文 (普通话)", "机械战甲"},
    {"Chinese (Mandarin)_Kind-hearted_Antie", "中文 (普通话)", "热心大婶"},
    {"Chinese (Mandarin)_HK_Flight_Attendant", "中文 (普通话)", "港普空姐"},
    {"Chinese (Mandarin)_Humorous_Elder", "中文 (普通话)", "搞笑大爷"},
    {"Chinese (Mandarin)_Gentleman", "中文 (普通话)", "温润男声"},
    {"Chinese (Mandarin)_Warm_Bestie", "中文 (普通话)", "温暖闺蜜"},
    {"Chinese (Mandarin)_Male_Announcer", "中文 (普通话)", "播报男声"},
    {"Chinese (Mandarin)_Sweet_Lady", "中文 (普通话)", "甜美女声"},
    {"Chinese (Mandarin)_Southern_Young_Man", "中文 (普通话)", "南方小哥"},
    {"Chinese (Mandarin)_Wise_Women", "中文 (普通话)", "阅历姐姐"},
    {"Chinese (Mandarin)_Gentle_Youth", "中文 (普通话)", "温润青年"},
    {"Chinese (Mandarin)_Warm_Girl", "中文 (普通话)", "温暖少女"},
    {"Chinese (Mandarin)_Kind-hearted_Elder", "中文 (普通话)", "花甲奶奶"},
    {"Chinese (Mandarin)_Cute_Spirit", "中文 (普通话)", "憨憨萌兽"},
    {"Chinese (Mandarin)_Radio_Host", "中文 (普通话)", "电台男主播"},
    {"Chinese (Mandarin)_Lyrical_Voice", "中文 (普通话)", "抒情男声"},
    {"Chinese (Mandarin)_Straightforward_Boy", "中文 (普通话)", "率真弟弟"},
    {"Chinese (Mandarin)_Sincere_Adult", "中文 (普通话)", "真诚青年"},
    {"Chinese (Mandarin)_Gentle_Senior", "中文 (普通话)", "温柔学姐"},
    {"Chinese (Mandarin)_Stubborn_Friend", "中文 (普通话)", "嘴硬竹马"},
    {"Chinese (Mandarin)_Crisp_Girl", "中文 (普通话)", "清脆少女"},
    {"Chinese (Mandarin)_Pure-hearted_Boy", "中文 (普通话)", "清澈邻家弟弟"},
    {"Chinese (Mandarin)_Soft_Girl", "中文 (普通话)", "柔和少女"},
    {"Cantonese_ProfessionalHost（F)", "中文 (粤语)", "专业女主持"},
    {"Cantonese_GentleLady", "中文 (粤语)", "温柔女声"},
    {"Cantonese_ProfessionalHost（M)", "中文 (粤语)", "专业男主持"},
    {"Cantonese_PlayfulMan", "中文 (粤语)", "活泼男声"},
    {"Cantonese_CuteGirl", "中文 (粤语)", "可爱女孩"},
    {"Cantonese_KindWoman", "中文 (粤语)", "善良女声"},
    {"Santa_Claus", "英文", "Santa Claus"},
    {"Grinch", "英文", "Grinch"},
    {"Rudolph", "英文", "Rudolph"},
    {"Arnold", "英文", "Arnold"},
    {"Charming_Santa", "英文", "Charming Santa"},
    {"Charming_Lady", "英文", "Charming Lady"},
    {"Sweet_Girl", "英文", "Sweet Girl"},
    {"Cute_Elf", "英文", "Cute Elf"},
    {"Attractive_Girl", "英文", "Attractive Girl"},
    {"Serene_Woman", "英文", "Serene Woman"},
    {"English_Trustworthy_Man", "英文", "Trustworthy Man"},
    {"English_Graceful_Lady", "英文", "Graceful Lady"},
    {"English_Aussie_Bloke", "英文", "Aussie Bloke"},
    {"English_Whispering_girl", "英文", "Whispering girl"},
    {"English_Diligent_Man", "英文", "Diligent Man"},
    {"English_Gentle-voiced_man", "英文", "Gentle-voiced man"},
    {"Japanese_IntellectualSenior", "日文", "Intellectual Senior"},
    {"Japanese_DecisivePrincess", "日文", "Decisive Princess"},
    {"Japanese_LoyalKnight", "日文", "Loyal Knight"},
    {"Japanese_DominantMan", "日文", "Dominant Man"},
    {"Japanese_SeriousCommander", "日文", "Serious Commander"},
    {"Japanese_ColdQueen", "日文", "Cold Queen"},
    {"Japanese_DependableWoman", "日文", "Dependable Woman"},
    {"Japanese_GentleButler", "日文", "Gentle Butler"},
    {"Japanese_KindLady", "日文", "Kind Lady"},
    {"Japanese_CalmLady", "日文", "Calm Lady"},
    {"Japanese_OptimisticYouth", "日文", "Optimistic Youth"},
    {"Japanese_GenerousIzakayaOwner", "日文", "Generous Izakaya Owner"},
    {"Japanese_SportyStudent", "日文", "Sporty Student"},
    {"Japanese_InnocentBoy", "日文", "Innocent Boy"},
    {"Japanese_GracefulMaiden", "日文", "Graceful Maiden"},
    {"Korean_SweetGirl", "韩文", "Sweet Girl"},
    {"Korean_CheerfulBoyfriend", "韩文", "Cheerful Boyfriend"},
    {"Korean_EnchantingSister", "韩文", "Enchanting Sister"},
    {"Korean_ShyGirl", "韩文", "Shy Girl"},
    {"Korean_ReliableSister", "韩文", "Reliable Sister"},
    {"Korean_StrictBoss", "韩文", "Strict Boss"},
    {"Korean_SassyGirl", "韩文", "Sassy Girl"},
    {"Korean_ChildhoodFriendGirl", "韩文", "Childhood Friend Girl"},
    {"Korean_PlayboyCharmer", "韩文", "Playboy Charmer"},
    {"Korean_ElegantPrincess", "韩文", "Elegant Princess"},
    {"Korean_BraveFemaleWarrior", "韩文", "Brave Female Warrior"},
    {"Korean_BraveYouth", "韩文", "Brave Youth"},
    {"Korean_CalmLady", "韩文", "Calm Lady"},
    {"Korean_EnthusiasticTeen", "韩文", "Enthusiastic Teen"},
    {"Korean_SoothingLady", "韩文", "Soothing Lady"},
    {"Korean_IntellectualSenior", "韩文", "Intellectual Senior"},
    {"Korean_LonelyWarrior", "韩文", "Lonely Warrior"},
    {"Korean_MatureLady", "韩文", "Mature Lady"},
    {"Korean_InnocentBoy", "韩文", "Innocent Boy"},
    {"Korean_CharmingSister", "韩文", "Charming Sister"},
    {"Korean_AthleticStudent", "韩文", "Athletic Student"},
    {"Korean_BraveAdventurer", "韩文", "Brave Adventurer"},
    {"Korean_CalmGentleman", "韩文", "Calm Gentleman"},
    {"Korean_WiseElf", "韩文", "Wise Elf"},
    {"Korean_CheerfulCoolJunior", "韩文", "Cheerful Cool Junior"},
    {"Korean_DecisiveQueen", "韩文", "Decisive Queen"},
    {"Korean_ColdYoungMan", "韩文", "Cold Young Man"},
    {"Korean_MysteriousGirl", "韩文", "Mysterious Girl"},
    {"Korean_QuirkyGirl", "韩文", "Quirky Girl"},
    {"Korean_ConsiderateSenior", "韩文", "Considerate Senior"},
    {"Korean_CheerfulLittleSister", "韩文", "Cheerful Little Sister"},
    {"Korean_DominantMan", "韩文", "Dominant Man"},
    {"Korean_AirheadedGirl", "韩文", "Airheaded Girl"},
    {"Korean_ReliableYouth", "韩文", "Reliable Youth"},
    {"Korean_FriendlyBigSister", "韩文", "Friendly Big Sister"},
    {"Korean_GentleBoss", "韩文", "Gentle Boss"},
    {"Korean_ColdGirl", "韩文", "Cold Girl"},
    {"Korean_HaughtyLady", "韩文", "Haughty Lady"},
    {"Korean_CharmingElderSister", "韩文", "Charming Elder Sister"},
    {"Korean_IntellectualMan", "韩文", "Intellectual Man"},
    {"Korean_CaringWoman", "韩文", "Caring Woman"},
    {"Korean_WiseTeacher", "韩文", "Wise Teacher"},
    {"Korean_ConfidentBoss", "韩文", "Confident Boss"},
    {"Korean_AthleticGirl", "韩文", "Athletic Girl"},
    {"Korean_PossessiveMan", "韩文", "Possessive Man"},
    {"Korean_GentleWoman", "韩文", "Gentle Woman"},
    {"Korean_CockyGuy", "韩文", "Cocky Guy"},
    {"Korean_ThoughtfulWoman", "韩文", "Thoughtful Woman"},
    {"Korean_OptimisticYouth", "韩文", "Optimistic Youth"},
    {"Spanish_SereneWoman", "西班牙文", "Serene Woman"},
    {"Spanish_MaturePartner", "西班牙文", "Mature Partner"},
    {"Spanish_CaptivatingStoryteller", "西班牙文", "Captivating Storyteller"},
    {"Spanish_Narrator", "西班牙文", "Narrator"},
    {"Spanish_WiseScholar", "西班牙文", "Wise Scholar"},
    {"Spanish_Kind-heartedGirl", "西班牙文", "Kind-hearted Girl"},
    {"Spanish_DeterminedManager", "西班牙文", "Determined Manager"},
    {"Spanish_BossyLeader", "西班牙文", "Bossy Leader"},
    {"Spanish_ReservedYoungMan", "西班牙文", "Reserved Young Man"},
    {"Spanish_ConfidentWoman", "西班牙文", "Confident Woman"},
    {"Spanish_ThoughtfulMan", "西班牙文", "Thoughtful Man"},
    {"Spanish_Strong-WilledBoy", "西班牙文", "Strong-willed Boy"},
    {"Spanish_SophisticatedLady", "西班牙文", "Sophisticated Lady"},
    {"Spanish_RationalMan", "西班牙文", "Rational Man"},
    {"Spanish_AnimeCharacter", "西班牙文", "Anime Character"},
    {"Spanish_Deep-tonedMan", "西班牙文", "Deep-toned Man"},
    {"Spanish_Fussyhostess", "西班牙文", "Fussy hostess"},
    {"Spanish_SincereTeen", "西班牙文", "Sincere Teen"},
    {"Spanish_FrankLady", "西班牙文", "Frank Lady"},
    {"Spanish_Comedian", "西班牙文", "Comedian"},
    {"Spanish_Debator", "西班牙文", "Debator"},
    {"Spanish_ToughBoss", "西班牙文", "Tough Boss"},
    {"Spanish_Wiselady", "西班牙文", "Wise Lady"},
    {"Spanish_Steadymentor", "西班牙文", "Steady Mentor"},
    {"Spanish_Jovialman", "西班牙文", "Jovial Man"},
    {"Spanish_SantaClaus", "西班牙文", "Santa Claus"},
    {"Spanish_Rudolph", "西班牙文", "Rudolph"},
    {"Spanish_Intonategirl", "西班牙文", "Intonate Girl"},
    {"Spanish_Arnold", "西班牙文", "Arnold"},
    {"Spanish_Ghost", "西班牙文", "Ghost"},
    {"Spanish_HumorousElder", "西班牙文", "Humorous Elder"},
    {"Spanish_EnergeticBoy", "西班牙文", "Energetic Boy"},
    {"Spanish_WhimsicalGirl", "西班牙文", "Whimsical Girl"},
    {"Spanish_StrictBoss", "西班牙文", "Strict Boss"},
    {"Spanish_ReliableMan", "西班牙文", "Reliable Man"},
    {"Spanish_SereneElder", "西班牙文", "Serene Elder"},
    {"Spanish_AngryMan", "西班牙文", "Angry Man"},
    {"Spanish_AssertiveQueen", "西班牙文", "Assertive Queen"},
    {"Spanish_CaringGirlfriend", "西班牙文", "Caring Girlfriend"},
    {"Spanish_PowerfulSoldier", "西班牙文", "Powerful Soldier"},
    {"Spanish_PassionateWarrior", "西班牙文", "Passionate Warrior"},
    {"Spanish_ChattyGirl", "西班牙文", "Chatty Girl"},
    {"Spanish_RomanticHusband", "西班牙文", "Romantic Husband"},
    {"Spanish_CompellingGirl", "西班牙文", "Compelling Girl"},
    {"Spanish_PowerfulVeteran", "西班牙文", "Powerful Veteran"},
    {"Spanish_SensibleManager", "西班牙文", "Sensible Manager"},
    {"Spanish_ThoughtfulLady", "西班牙文", "Thoughtful Lady"},
    {"Portuguese_SentimentalLady", "葡萄牙文", "Sentimental Lady"},
    {"Portuguese_BossyLeader", "葡萄牙文", "Bossy Leader"},
    {"Portuguese_Wiselady", "葡萄牙文", "Wise lady"},
    {"Portuguese_Strong-WilledBoy", "葡萄牙文", "Strong-willed Boy"},
    {"Portuguese_Deep-VoicedGentleman", "葡萄牙文", "Deep-voiced Gentleman"},
    {"Portuguese_UpsetGirl", "葡萄牙文", "Upset Girl"},
    {"Portuguese_PassionateWarrior", "葡萄牙文", "Passionate Warrior"},
    {"Portuguese_AnimeCharacter", "葡萄牙文", "Anime Character"},
    {"Portuguese_ConfidentWoman", "葡萄牙文", "Confident Woman"},
    {"Portuguese_AngryMan", "葡萄牙文", "Angry Man"},
    {"Portuguese_CaptivatingStoryteller", "葡萄牙文", "Captivating Storyteller"},
    {"Portuguese_Godfather", "葡萄牙文", "Godfather"},
    {"Portuguese_ReservedYoungMan", "葡萄牙文", "Reserved Young Man"},
    {"Portuguese_SmartYoungGirl", "葡萄牙文", "Smart Young Girl"},
    {"Portuguese_Kind-heartedGirl", "葡萄牙文", "Kind-hearted Girl"},
    {"Portuguese_Pompouslady", "葡萄牙文", "Pompous lady"},
    {"Portuguese_Grinch", "葡萄牙文", "Grinch"},
    {"Portuguese_Debator", "葡萄牙文", "Debator"},
    {"Portuguese_SweetGirl", "葡萄牙文", "Sweet Girl"},
    {"Portuguese_AttractiveGirl", "葡萄牙文", "Attractive Girl"},
    {"Portuguese_ThoughtfulMan", "葡萄牙文", "Thoughtful Man"},
    {"Portuguese_PlayfulGirl", "葡萄牙文", "Playful Girl"},
    {"Portuguese_GorgeousLady", "葡萄牙文", "Gorgeous Lady"},
    {"Portuguese_LovelyLady", "葡萄牙文", "Lovely Lady"},
    {"Portuguese_SereneWoman", "葡萄牙文", "Serene Woman"},
    {"Portuguese_SadTeen", "葡萄牙文", "Sad Teen"},
    {"Portuguese_MaturePartner", "葡萄牙文", "Mature Partner"},
    {"Portuguese_Comedian", "葡萄牙文", "Comedian"},
    {"Portuguese_NaughtySchoolgirl", "葡萄牙文", "Naughty Schoolgirl"},
    {"Portuguese_Narrator", "葡萄牙文", "Narrator"},
    {"Portuguese_ToughBoss", "葡萄牙文", "Tough Boss"},
    {"Portuguese_Fussyhostess", "葡萄牙文", "Fussy hostess"},
    {"Portuguese_Dramatist", "葡萄牙文", "Dramatist"},
    {"Portuguese_Steadymentor", "葡萄牙文", "Steady Mentor"},
    {"Portuguese_Jovialman", "葡萄牙文", "Jovial Man"},
    {"Portuguese_CharmingQueen", "葡萄牙文", "Charming Queen"},
    {"Portuguese_SantaClaus", "葡萄牙文", "Santa Claus"},
    {"Portuguese_Rudolph", "葡萄牙文", "Rudolph"},
    {"Portuguese_Arnold", "葡萄牙文", "Arnold"},
    {"Portuguese_CharmingSanta", "葡萄牙文", "Charming Santa"},
    {"Portuguese_CharmingLady", "葡萄牙文", "Charming Lady"},
    {"Portuguese_Ghost", "葡萄牙文", "Ghost"},
    {"Portuguese_HumorousElder", "葡萄牙文", "Humorous Elder"},
    {"Portuguese_CalmLeader", "葡萄牙文", "Calm Leader"},
    {"Portuguese_GentleTeacher", "葡萄牙文", "Gentle Teacher"},
    {"Portuguese_EnergeticBoy", "葡萄牙文", "Energetic Boy"},
    {"Portuguese_ReliableMan", "葡萄牙文", "Reliable Man"},
    {"Portuguese_SereneElder", "葡萄牙文", "Serene Elder"},
    {"Portuguese_GrimReaper", "葡萄牙文", "Grim Reaper"},
    {"Portuguese_AssertiveQueen", "葡萄牙文", "Assertive Queen"},
    {"Portuguese_WhimsicalGirl", "葡萄牙文", "Whimsical Girl"},
    {"Portuguese_StressedLady", "葡萄牙文", "Stressed Lady"},
    {"Portuguese_FriendlyNeighbor", "葡萄牙文", "Friendly Neighbor"},
    {"Portuguese_CaringGirlfriend", "葡萄牙文", "Caring Girlfriend"},
    {"Portuguese_PowerfulSoldier", "葡萄牙文", "Powerful Soldier"},
    {"Portuguese_FascinatingBoy", "葡萄牙文", "Fascinating Boy"},
    {"Portuguese_RomanticHusband", "葡萄牙文", "Romantic Husband"},
    {"Portuguese_StrictBoss", "葡萄牙文", "Strict Boss"},
    {"Portuguese_InspiringLady", "葡萄牙文", "Inspiring Lady"},
    {"Portuguese_PlayfulSpirit", "葡萄牙文", "Playful Spirit"},
    {"Portuguese_ElegantGirl", "葡萄牙文", "Elegant Girl"},
    {"Portuguese_CompellingGirl", "葡萄牙文", "Compelling Girl"},
    {"Portuguese_PowerfulVeteran", "葡萄牙文", "Powerful Veteran"},
    {"Portuguese_SensibleManager", "葡萄牙文", "Sensible Manager"},
    {"Portuguese_ThoughtfulLady", "葡萄牙文", "Thoughtful Lady"},
    {"Portuguese_TheatricalActor", "葡萄牙文", "Theatrical Actor"},
    {"Portuguese_FragileBoy", "葡萄牙文", "Fragile Boy"},
    {"Portuguese_ChattyGirl", "葡萄牙文", "Chatty Girl"},
    {"Portuguese_Conscientiousinstructor", "葡萄牙文", "Conscientious Instructor"},
    {"Portuguese_RationalMan", "葡萄牙文", "Rational Man"},
    {"Portuguese_WiseScholar", "葡萄牙文", "Wise Scholar"},
    {"Portuguese_FrankLady", "葡萄牙文", "Frank Lady"},
    {"Portuguese_DeterminedManager", "葡萄牙文", "Determined Manager"},
    {"French_Male_Speech_New", "法文", "Level-Headed Man"},
    {"French_Female_News Anchor", "法文", "Patient Female Presenter"},
    {"French_CasualMan", "法文", "Casual Man"},
    {"French_MovieLeadFemale", "法文", "Movie Lead Female"},
    {"French_FemaleAnchor", "法文", "Female Anchor"},
    {"French_MaleNarrator", "法文", "Male Narrator"},
    {"Indonesian_SweetGirl", "印尼文", "Sweet Girl"},
    {"Indonesian_ReservedYoungMan", "印尼文", "Reserved Young Man"},
    {"Indonesian_CharmingGirl", "印尼文", "Charming Girl"},
    {"Indonesian_CalmWoman", "印尼文", "Calm Woman"},
    {"Indonesian_ConfidentWoman", "印尼文", "Confident Woman"},
    {"Indonesian_CaringMan", "印尼文", "Caring Man"},
    {"Indonesian_BossyLeader", "印尼文", "Bossy Leader"},
    {"Indonesian_DeterminedBoy", "印尼文", "Determined Boy"},
    {"Indonesian_GentleGirl", "印尼文", "Gentle Girl"},
    {"German_FriendlyMan", "德文", "Friendly Man"},
    {"German_SweetLady", "德文", "Sweet Lady"},
    {"German_PlayfulMan", "德文", "Playful Man"},
    {"Russian_HandsomeChildhoodFriend", "俄文", "Handsome Childhood Friend"},
    {"Russian_BrightHeroine", "俄文", "Bright Queen"},
    {"Russian_AmbitiousWoman", "俄文", "Ambitious Woman"},
    {"Russian_ReliableMan", "俄文", "Reliable Man"},
    {"Russian_CrazyQueen", "俄文", "Crazy Girl"},
    {"Russian_PessimisticGirl", "俄文", "Pessimistic Girl"},
    {"Russian_AttractiveGuy", "俄文", "Attractive Guy"},
    {"Russian_Bad-temperedBoy", "俄文", "Bad-tempered Boy"},
    {"Italian_BraveHeroine", "意大利文", "Brave Heroine"},
    {"Italian_Narrator", "意大利文", "Narrator"},
    {"Italian_WanderingSorcerer", "意大利文", "Wandering Sorcerer"},
    {"Italian_DiligentLeader", "意大利文", "Diligent Leader"},
    {"Arabic_CalmWoman", "阿拉伯文", "Calm Woman"},
    {"Arabic_FriendlyGuy", "阿拉伯文", "Friendly Guy"},
    {"Turkish_CalmWoman", "土耳其文", "Calm Woman"},
    {"Turkish_Trustworthyman", "土耳其文", "Trustworthy man"},
    {"Ukrainian_CalmWoman", "乌克兰文", "Calm Woman"},
    {"Ukrainian_WiseScholar", "乌克兰文", "Wise Scholar"},
    {"Dutch_kindhearted_girl", "荷兰文", "Kind-hearted girl"},
    {"Dutch_bossy_leader", "荷兰文", "Bossy leader"},
    {"Vietnamese_kindhearted_girl", "越南文", "Kind-hearted girl"},
    {"Thai_male_1_sample8", "泰文", "Serene Man"},
    {"Thai_male_2_sample2", "泰文", "Friendly Man"},
    {"Thai_female_1_sample1", "泰文", "Confident Woman"},
    {"Thai_female_2_sample2", "泰文", "Energetic Woman"},
    {"Polish_male_1_sample4", "波兰文", "Male Narrator"},
    {"Polish_male_2_sample3", "波兰文", "Male Anchor"},
    {"Polish_female_1_sample1", "波兰文", "Calm Woman"},
    {"Polish_female_2_sample3", "波兰文", "Casual Woman"},
    {"Romanian_male_1_sample2", "罗马尼亚文", "Reliable Man"},
    {"Romanian_male_2_sample1", "罗马尼亚文", "Energetic Youth"},
    {"Romanian_female_1_sample4", "罗马尼亚文", "Optimistic Youth"},
    {"Romanian_female_2_sample1", "罗马尼亚文", "Gentle Woman"},
    {"greek_male_1a_v1", "希腊文", "Thoughtful Mentor"},
    {"Greek_female_1_sample1", "希腊文", "Gentle Lady"},
    {"Greek_female_2_sample3", "希腊文", "Girl Next Door"},
    {"czech_male_1_v1", "捷克文", "Assured Presenter"},
    {"czech_female_5_v7", "捷克文", "Steadfast Narrator"},
    {"czech_female_2_v2", "捷克文", "Elegant Lady"},
    {"finnish_male_3_v1", "芬兰文", "Upbeat Man"},
    {"finnish_male_1_v2", "芬兰文", "Friendly Boy"},
    {"finnish_female_4_v1", "芬兰文", "Assetive Woman"},
    {"hindi_male_1_v2", "印地文", "Trustworthy Advisor"},
    {"hindi_female_2_v1", "印地文", "Tranquil Woman"},
    {"hindi_female_1_v2", "印地文", "News Anchor"}
  ]

  def options do
    Enum.map(@voices, fn {native_id, language, name} ->
      {native_id, "#{name} (#{language})"}
    end)
  end

  def valid?(native_id) when is_binary(native_id) do
    Enum.any?(@voices, fn {voice_id, _language, _name} -> voice_id == native_id end)
  end

  def valid?(_native_id), do: false
end
